### ISSUE TITLE
No Such File or Directory Error : `prerender-manifest.json`

### ISSUE THREAD

**Issue by calendee** [ericclemmons/codelift#84]
Hello,

Info:
- macOS 10.15.3
- yarn 1.21.1
- node v10.16.3 or v12.14.1 or v12.16.1

I just started dabbling with Codelift.  I followed the instructions:

```
yarn create next-app --example with-tailwindcss with-tailwindcss-app
cd with-tailwindcss-app
yarn add codelift --dev
```

Change CSS:

```
/* purgecss start ignore */
@tailwind base;
@tailwind components;
@tailwind utilities;
/* purgecss end ignore */...
```

Finally, `yarn codelift dev`.

This is the result:

```
yarn codelift dev
yarn run v1.21.1
warning package.json: No license field
warning ../../../package.json: No license field
$ /Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/.bin/codelift dev
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/codelift/.next/prerender-manifest.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.initializeSprCache (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/next-server/server/spr-cache.js:53:53)
    at new Server (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/next-server/server/next-server.js:92:21)
    at createServer (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/server/next.js:2:133)
    at Object.<anonymous> (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/codelift/server.js:18:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I did try to just start the app without Codelift with `yarn start` but received:

```
yarn run v1.21.1
warning package.json: No license field
warning ../../../package.json: No license field
$ next start
Error: Could not find a valid build in the '/Users/jn/Documents/Apps/with-tailwindcss-app/.next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/next-server/server/next-server.js:818:23)
    at new Server (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/next-server/server/next-server.js:52:29)
    at createServer (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/server/next.js:2:133)
    at start (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/server/lib/start-server.js:1:323)
    at nextStart (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/cli/next-start.js:22:125)
    at commands.(anonymous function).then.exec (/Users/jn/Documents/Apps/with-tailwindcss-app/node_modules/next/dist/bin/next:29:339)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So, I tried `yarn next build` and then `yarn start` which all worked fine.

After that, I tried `yarn codelift dev` again with the same results.

Any ideas?

**Comment by ericclemmons** [comment]
I’m able to reproduce and will get this fixed. Thanks!

**Comment by ericclemmons** [comment]
First thing I forgot to point out, unlike create-react-app, `yarn start` runs the _production_ build with Next.js.  `yarn dev` is the correct command for local development.

I opened #85 to ensure that codelift uses it's own version of Next, rather than the one in the host application.
